version: '3'
services:
  app:
    container_name: portfolio-react-node
    restart: always
    build: .
    expose:
      - 80
    restart: always
#     volumes: ['./:/var/www/html']
    environment:
      VIRTUAL_HOST: robertmsoriano.com
      LETSENCRYPT_HOST: robertmsoriano.com
      LETSENCRYPT_EMAIL: robertomsoriano@hotmail.com
networks:
  default:
    external:
      name: nginx-proxy