version: '3'
services:
  app:
    container_name: portfolio-react-node
    restart: always
    build: .
    # ports:
    #   - '80:5000'
    expose:
      - 80
    restart: always
#     volumes: ['./:/var/www/html']
#     environment:
#       VIRTUAL_HOST: robertoms.tk
#       LETSENCRYPT_HOST: robertoms.tk
#       LETSENCRYPT_EMAIL: robertomsoriano@hotmail.com
# networks:
#   default:
#     external:
#       name: nginx-proxy