import React from "react";
import HomeButton from "./homepage/HomeButton";
const AboutMe = () => {
  return (
    <div className="container">
      <br />
      <br />
      <h2 style={{ textAlign: "center" }}>Who is this guy?</h2>
      <section>
        <br />
        <br />
        <p> Glad you asked!</p>
        <div
          className="container"
          style={{ marginBottom: "200px", fontSize: "20px" }}
        >
          <p>
            I'm a <strong>software developer</strong>, who loves to engineer web
            applications that satisfy specific needs. I consider myself a
            technical person, who <strong>analyzes details</strong> to arrive at
            accurate conclusions. My interests in development arise, not so much
            from just "wanting to build stuff", though <strong>I enjoy</strong>{" "}
            this aspect of making web apps, but from the satisfaction and reward
            generated by the problem identification/solving process.
            <br />
            <br />I have the necessary <strong>skills</strong> to help
            businesses establish their online presence and take advantage of the
            opportunities the web offers.{" "}
          </p>
          <p>
            Some of my favorite technologies for{" "}
            <strong>front-end development</strong> are ReactJS, Sanity CMS and
            Vanilla JavaScript. For <strong>backend-development</strong>, I
            enjoy using NodeJS, ExpressJS, GraphQL and I also have experience
            with Django, its REST framework, and SQLite.
          </p>
          <p>
            <strong>For deployment</strong>, though I have tried, and love, free
            services like GitHub Pages and Netlify for single-page-applications,
            I now deploy to <strong>my own Linux VPS</strong> where I run an
            automated Nginx reverse proxy for <strong>Docker containers</strong>
            . I containerize my apps and then ship them to the Web, with my own
            domains, with no hassle at all.
          </p>
          <HomeButton text={"Some of my Projects"} link={"/projects"} />
          <br />
          <p>
            I use Visual Studio Code for code editing, NPM and Yarn for package
            management, and Git for version control.
          </p>
          <p>
            I also have experience working in <strong>data analysis</strong>. I
            have completed an Udacity Data Analytics Nanodegree, which taught me
            the basics of data science and helped me improve (and put to use) my{" "}
            <strong>Python, SQL and statistics skills</strong>. I learned how to
            discover insights from chunk of raw data and communicate my findings
            using visualizations with libraries like NumPy, Pandas and
            MatPlotLib.{" "}
          </p>
          <p style={{ textAlign: "center" }}>
            <strong>Get to know me better!</strong>
            <br />
            <br /> Shoot me a message to schedule an interview:
          </p>
          <HomeButton text={"Contact Me"} link={"/contact"} />
        </div>
      </section>
    </div>
  );
};

export default AboutMe;
